import Head from "next/head";
const Layout = ({ title, children }) => {
  return (
    //   main wrapper
    <div className="bg-gray-300">
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* centered container taking full page */}
      <main className="container mx-auto max-w-xl pt-8 min-h-screen">
        {children}
      </main>
    </div>
  );
};

export default Layout;
